@startuml Domain Model
left to right direction

hide circle
hide members

mix_actor ユーザー
mix_actor バフェットコード

class 優先市場
class 企業
class 決算短信
class 有価証券報告書

ユーザー --o 企業
企業 --o 決算短信
企業 --o 有価証券報告書
優先市場 o-- 企業
企業 --o バフェットコード

@enduml
