@startuml Domain Model
left to right direction

hide circle
hide methods
hide members

mix_actor ユーザー

class 市場
class 企業
class 財務諸表
class 株価
class バフェットコード

ユーザー o-- 企業
企業 o-- 市場
企業 --o 財務諸表
企業 --o 株価

@enduml
